# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__) #numpy 버전 확인
np.show_config()

1.22.3
openblas64__info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SU

#### 3. Create a null vector of size 10 (★☆☆)

In [48]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [35]:
x = np.array([100,20,34])
  
print("Size of the array: ", x.size)
  
print("Memory size of one array element in bytes: ", x.itemsize)
  
# memory size of numpy array in bytes
print("Memory size of numpy array in bytes:", x.size * x.itemsize)

Size of the array:  3
Memory size of one array element in bytes:  4
Memory size of numpy array in bytes: 12


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [36]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [49]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [50]:
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [51]:
x = np.array([4,24,2,6,53,13])

print(x[::-1])
print(np.flip(x))

[13 53  6  2 24  4]
[13 53  6  2 24  4]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [53]:
x = np.arange(0,9)
x = x.reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [56]:
x = np.array([1,2,0,0,4,0])
for i in range(len(x)):
    if x[i] != 0:
        print(i)
        
print(np.where(x != 0))
print(np.nonzero(x))

0
1
4
(array([0, 1, 4], dtype=int64),)
(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [57]:
x = np.eye(3,3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [60]:
x = np.random.random([3,3,3])
print(x)

print("\n")

y = np.random.randint(27, size=(3,3,3))
print(y)

[[[0.94662197 0.97786784 0.28630518]
  [0.45100529 0.76428167 0.97041551]
  [0.08993333 0.47186816 0.66638136]]

 [[0.98669282 0.20472619 0.58080612]
  [0.60683866 0.84179036 0.8975152 ]
  [0.83783521 0.79502286 0.79771912]]

 [[0.31884396 0.45646864 0.3685764 ]
  [0.3561038  0.4646008  0.40736881]
  [0.43417455 0.58501488 0.21263581]]]


[[[15 24 14]
  [ 7  2  5]
  [ 8 15 15]]

 [[19 25 21]
  [11  9 26]
  [ 0  7  5]]

 [[22 16 14]
  [20 11 14]
  [ 3 20 24]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [61]:
x = np.random.random([10,10])
print("array:", x)
print("\n")
print("최소값:", np.min(x)) #x.min
print("최대값:", np.max(x)) #x.max

array: [[0.15250254 0.32803227 0.55203165 0.98206562 0.39584576 0.27646566
  0.86303708 0.8686586  0.36631571 0.35690862]
 [0.32779387 0.94045617 0.79364084 0.97880195 0.83867724 0.3164721
  0.58665779 0.7517017  0.4384464  0.71880395]
 [0.88514076 0.8652135  0.85559814 0.34247681 0.82954789 0.81638593
  0.52840133 0.51547782 0.56786423 0.38684491]
 [0.65441415 0.51515142 0.29897303 0.11979284 0.51503604 0.42991052
  0.70540125 0.3631962  0.37574112 0.61690631]
 [0.61078753 0.27733429 0.63385141 0.75513326 0.42053983 0.35553352
  0.71808947 0.04196451 0.0469651  0.35758764]
 [0.97631338 0.27417787 0.8640416  0.22034256 0.7223597  0.76524155
  0.52053282 0.69827936 0.206971   0.60803217]
 [0.65772559 0.55694676 0.07240525 0.29828289 0.67826528 0.99014616
  0.31333398 0.20042451 0.3764155  0.02504638]
 [0.45795969 0.7630016  0.31664127 0.66078811 0.79012653 0.13843316
  0.73676503 0.09407515 0.21345487 0.86785595]
 [0.15035533 0.37546743 0.98874572 0.99828655 0.96667937 0.24696312
  0.83

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [62]:
x = np.random.random(30)
print(x)
print("평균:",np.mean(x)) #x.mean

[0.59101568 0.84912965 0.65621789 0.0602328  0.07110058 0.53370394
 0.7472945  0.30417914 0.44191455 0.11222854 0.19151765 0.23620133
 0.59032453 0.71619254 0.76384941 0.3533908  0.59178301 0.22068257
 0.22640909 0.47565739 0.79691381 0.63852416 0.32533308 0.49613109
 0.19529569 0.29165299 0.72276359 0.61478036 0.85505104 0.80796797]
평균: 0.4825813121513779


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [65]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [68]:
x = np.ones((5,5))
y = np.pad(array=x, pad_width=1, mode='constant')
print(x)
print("\n")
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [71]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [72]:
x = np.array([1, 2, 3, 4])
np.diag(x)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [78]:
#x[a:b:c] -> index a부터 b-1까지 c칸 간격으로 추출
x = np.zeros((8,8))
x[1::2,::2] = 1 #row: 1부터 끝까지 2칸 간격으로, col: 처음부터 끝까지 2칸 간격으로
x[::2,1::2] = 1 #row: 처음부터 끝까지 2칸 간격으로, col: 1부터 끝까지 2칸 간격으로
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [81]:
x = np.unravel_index(99, (6,7,8)) #(6,7,8) shape array에서 100번째 element의 위치
print(x)

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [4]:
x = np.tile(np.array([[0,1],[1,0]]),(4,4)) #2x2 matrix 만들고 가로 4번, 세로 4번 반복
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [85]:
x = np.random.random((5,5))
normal_x = (x - np.mean(x)) / np.std(x)
print("random matirx:\n", x)
print("\n")
print("normalized matrix:\n", normal_x)

random matirx:
 [[0.56584248 0.22300817 0.98265691 0.29851752 0.01635447]
 [0.57839633 0.72071472 0.82859114 0.26598339 0.6283073 ]
 [0.30170327 0.42662545 0.59486781 0.62322202 0.94310859]
 [0.08764997 0.10613468 0.68329499 0.55579322 0.66074683]
 [0.65687178 0.94935866 0.74288403 0.20021784 0.44958105]]


normalized matrix:
 [[ 0.15566423 -1.10820362  1.69226183 -0.82983639 -1.87003804]
 [ 0.20194434  0.72660491  1.12429421 -0.94977434  0.38594248]
 [-0.81809205 -0.35756306  0.26266691  0.36719545  1.54646587]
 [-1.60720527 -1.53906091  0.58865605  0.11861739  0.50553166]
 [ 0.49124619  1.56950693  0.80833267 -1.1922208  -0.27293664]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [86]:
col = np.dtype([('r', np.ubyte,1),
               ('g', np.ubyte,1),
               ('b', np.ubyte,1),
               ('a', np.ubyte,1)])
print(col)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


<ipython-input-86-6b7333104554>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  col = np.dtype([('r', np.ubyte,1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [87]:
A = np.random.random((5,3))
B = np.random.random((3,2))
print(A@B)
print("\n")
print(np.dot(A,B))

[[0.80440278 1.05427281]
 [0.80143242 1.06461897]
 [0.75037277 0.99990148]
 [0.80956596 1.04425262]
 [0.7048591  0.93172211]]


[[0.80440278 1.05427281]
 [0.80143242 1.06461897]
 [0.75037277 0.99990148]
 [0.80956596 1.04425262]
 [0.7048591  0.93172211]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [65]:
x = np.arange(11)
x[(x>3) & (x<8)] *= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [1]:
print(sum(range(5),-1)) #sum: python의 내장 함수 -> 모든 원소의 합 출력
from numpy import * #numpy의 모든 함수 import (sum함수도 import됨)
print(sum(range(5),-1)) #sum: numpy의 내장 함수 -> sum(더해줄 숫자,axis): axis=-1이므로 column끼리의 합 출력

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [98]:
Z = np.array([1,2,3])
print(Z**Z) #1**1, 2**2, 3**3
print(2 << Z >> 2) #2를 Z만큼 left shift한 후 세 개의 값을 2만큼 right shift
print(Z <- Z) #Z가 -Z보다 작은지 확인
print(1j*Z) #1j = i (허수)
print(Z/1/1) #Z를 1로 두 번 나누기
#print(Z<Z>Z) #오류 발생

[ 1  4 27]
[1 2 4]
[False False False]
[0.+1.j 0.+2.j 0.+3.j]
[1. 2. 3.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [92]:
np.array(0) / np.array(0) #nan
np.array(0) // np.array(0) #0
np.array([np.nan]).astype(int).astype(float)

<ipython-input-92-cd809174da5d>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
<ipython-input-92-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [101]:
x = np.random.uniform(-10,+10,10) #균등분포에 맞게 무작위 표본 추출 (low,high,size)
print(x,"\n")
#np.copysign(x1,x2): x2의 부호를 그대로 x1에 적용
print(np.copysign(np.ceil(np.abs(x)),x)) #절댓값을 취한 상태로 올림을 해주고 copysign() 메소드를 통해 기존의 부호대로 변경

[-3.16342617 -8.82392663  7.12278987  0.06979683  1.55602005 -3.7921838
 -9.08002654  9.3516986   5.80803646  0.3745949 ] 

[ -4.  -9.   8.   1.   2.  -4. -10.  10.   6.   1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [104]:
array1 = np.array([0,10,20,40,60])
print("array1:", array1)
array2 = np.array([10,30,40])
print("array2:", array2)
#np.intersect1d(x,y): x와 y의 공통된 인자의 값(default)과 인덱스(return_indices=True 옵션) 반환
print("Common values between two arrays:", np.intersect1d(array1, array2))

array1: [ 0 10 20 40 60]
array2: [10 30 40]
Common values between two arrays: [10 40]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
#defaults = np.seterr(all="ignore") #오류 발생시 아무 행동도 취하지 않게 함

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [105]:
print(np.sqrt(-1)) #nan
print(np.emath.sqrt(-1)) #허수 반환
print(np.sqrt(-1) == np.emath.sqrt(-1))

nan
1j
False


<ipython-input-105-5b82f2e69cca>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1)) #nan
<ipython-input-105-5b82f2e69cca>:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [106]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D') #'D' 옵션: day
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
next_year = np.datetime64('today', 'M') + np.timedelta64(1, 'M') #'M' 옵션: month

print(yesterday)
print(today)
print(tomorrow)
print(next_year)

2022-03-16
2022-03-17
2022-03-18
2022-04


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [4]:
x = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [43]:
A = np.random.random(5)
B = np.random.random(5)

print("A:",A)
print("B:",B)

np.add(A,B,out=B) #A와 B를 더해서 B에 저장
print("\n<A+B>")
print("A:",A)
print("B:",B)

np.divide(A,2,out=A) #A를 2로 나눠서 A에 저장
print("\n<A/2>")
print("A:",A)
print("B:",B)

np.negative(A,out=A) #A에 - 붙여서 A에 저장
print("\n<-A>")
print("A:",A)
print("B:",B)

np.multiply(A,B,out=A) #A와 B를 곱해서 A에 저장
print("\n<A*B>")
print("A:",A)
print("B:",B)

A: [0.82055835 0.28102423 0.91881441 0.97601557 0.67028898]
B: [0.47681426 0.96485277 0.68555017 0.22671225 0.92717914]

<A+B>
A: [0.82055835 0.28102423 0.91881441 0.97601557 0.67028898]
B: [1.29737261 1.24587699 1.60436458 1.20272782 1.59746812]

<A/2>
A: [0.41027918 0.14051211 0.45940721 0.48800778 0.33514449]
B: [1.29737261 1.24587699 1.60436458 1.20272782 1.59746812]

<-A>
A: [-0.41027918 -0.14051211 -0.45940721 -0.48800778 -0.33514449]
B: [1.29737261 1.24587699 1.60436458 1.20272782 1.59746812]

<A*B>
A: [-0.53228497 -0.17506081 -0.73705665 -0.58694054 -0.53538264]
B: [1.29737261 1.24587699 1.60436458 1.20272782 1.59746812]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [53]:
x = np.random.uniform(0,10,10)

print("x:",x,"\n")
print("method 1:", x.astype(np.int32))
print("method 2:", np.trunc(x))
print("method 3:", x - x%1)
print("method 4:", np.floor(x))

x: [2.43300361 6.59664503 0.14247167 7.74127573 3.9986475  8.77378961
 0.21349878 5.03024414 7.44912771 7.04291072] 

method 1: [2 6 0 7 3 8 0 5 7 7]
method 2: [2. 6. 0. 7. 3. 8. 0. 5. 7. 7.]
method 3: [2. 6. 0. 7. 3. 8. 0. 5. 7. 7.]
method 4: [2. 6. 0. 7. 3. 8. 0. 5. 7. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [56]:
x = np.zeros((5,5))
x += np.arange(0,5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [60]:
def generator(): #iterator와 방식이 같음
    for i in range(10):
        yield i #하나씩 바로 return

#np.fromiter(iterable,dtype,count) -> iterable: 함수가 반복할 객체, dtype: 반환될 배열의 데이터 타입, count: 읽을 요소의 수 (default=-1: 다 읽음)
np.fromiter(generator(),dtype=np.float32,count=-1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [69]:
#np.linspace(start,stop,num,endpoint) -> start부터 stop까지를 일정한 간격으로 num개의 숫자로 만들어 반환, endpoin=True: stop을 포함
x = np.linspace(start=0,stop=1,num=11,endpoint=False)[1:] #0이 포함되었으므로 index 1부터 선택
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [77]:
x = np.random.random(10)
print("x:\n",x,"\n")

x.sort()
print("sorted x:\n", x) #np.sort(x)

x:
 [0.70220379 0.78616685 0.022014   0.57106597 0.36167359 0.55389002
 0.61764465 0.13802682 0.83412714 0.5084729 ] 

sorted x:
 [0.022014   0.13802682 0.36167359 0.5084729  0.55389002 0.57106597
 0.61764465 0.70220379 0.78616685 0.83412714]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [79]:
import time

begin_time1 = time.time()
x = np.arange(1000000)
np.sum(x) #np.sum() 함수 사용
end_time1 = time.time()
print("np.sum() 함수 사용:", str(1000*(end_time1 - begin_time1)))

begin_time2 = time.time()
x = np.arange(1000000)
np.add.reduce(x) #np.add.reduce() 함수 사용
end_time2 = time.time()
print("np.add.reduce() 함수 사용:",str(1000*(end_time2 - begin_time2)))

np.sum() 함수 사용: 2.991914749145508
np.add.reduce() 함수 사용: 1.9941329956054688


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [83]:
A = np.random.random(5)
B = np.random.random(5)
print(np.array_equal(A,B),"\n")

A = np.arange(5)
B = np.arange(5)
print(np.array_equal(A,B))

False 

True


#### 43. Make an array immutable (read-only) (★★☆)

In [86]:
x = np.zeros(10)
x.flags.writeable = False #변경 불가하도록 수정
x[0] = 1 #에러 발생

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [88]:
z = np.random.random((10,2))
x, y = z[:,0], z[:,1]
r = np.sqrt(x**2 + y**2)
p = np.arctan2(y,x)
print(r,"\n")
print(p)

[1.03689231 0.87696913 0.74813067 0.67597255 0.93270304 1.06172492
 0.62877488 0.39031733 0.41005135 1.1267588 ] 

[1.29642428 0.85175716 0.88189209 0.01125517 0.85242444 0.91213394
 1.20673606 0.46108733 0.07396087 0.53242273]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [93]:
x = np.random.random(10)
print("x:",x,"\n")
x[x == np.max(x)] = 0 #x[x.argmax()] = 0
print("x:",x)

x: [0.46046729 0.53154884 0.94885737 0.77982102 0.53577944 0.06365132
 0.16192478 0.6305017  0.98770893 0.26831415] 

x: [0.46046729 0.53154884 0.94885737 0.77982102 0.53577944 0.06365132
 0.16192478 0.6305017  0.         0.26831415]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [98]:
z = np.zeros((5,5),[('x',float),('y',float)])
print(z,"\n")
z['x'], z['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(z)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]] 

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [105]:
X = np.random.random(5)
Y = np.random.random(5)

print("X:\n",X)
print("Y:\n",Y,"\n")

C = 1.0 / np.subtract.outer(X,Y) #np.subtract.outer(X,Y): X-Y
print("C:\n",C,"\n")
print("determinant of C:\n",np.linalg.det(C))

X:
 [0.28745421 0.46978    0.04773958 0.55850674 0.87058398]
Y:
 [0.61477471 0.5612968  0.55905316 0.04306428 0.21121587] 

C:
 [[-3.05510963e+00 -3.65173296e+00 -3.68189944e+00  4.09182153e+00
   1.31167599e+01]
 [-6.89680359e+00 -1.09269561e+01 -1.12015760e+01  2.34348053e+00
   3.86751245e+00]
 [-1.76355917e+00 -1.94720270e+00 -1.95574702e+00  2.13889791e+02
  -6.11709499e+00]
 [-1.77721007e+01 -3.58415372e+02 -1.83010711e+03  1.94008075e+00
   2.87943074e+00]
 [ 3.90916240e+00  3.23324098e+00  3.20995520e+00  1.20843044e+00
   1.51660352e+00]] 

determinant of C:
 82433134.11406203


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [111]:
for dtype in [np.int8, np.int32, np.int64]:
    print(dtype)
    print(np.iinfo(dtype).min) #np.iinfo(): int에 대한 정보 return
    print(np.iinfo(dtype).max,"\n")

for dtype in [np.float32, np.float64]:
    print(dtype)
    print(np.finfo(dtype).min) #np.finfo(): float에 대한 정보 return
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps,"\n") #eps: 표현 가능한 가장 작은 값 return

<class 'numpy.int8'>
-128
127 

<class 'numpy.int32'>
-2147483648
2147483647 

<class 'numpy.int64'>
-9223372036854775808
9223372036854775807 

<class 'numpy.float32'>
-3.4028235e+38
3.4028235e+38
1.1920929e-07 

<class 'numpy.float64'>
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16 



#### 49. How to print all the values of an array? (★★☆)

In [117]:
np.set_printoptions(threshold=float("inf"))
x = np.zeros((40,40))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [123]:
x = np.arange(100)
v = np.random.uniform(0,100)
print("x:\n",x)
print("\nv:",v)
index = (np.abs(x-v)).argmin()
print("\ncloset value:",x[index])

x:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

v: 13.542973508565314

closet value: 14


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [124]:
z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-124-5d3109e3f61f>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [128]:
z = np.random.random((10,2))
x, y = np.atleast_2d(z[:,0],z[:,1])
D = np.sqrt( (x-x.T)**2 + (y-y.T)**2 )
print(D,"\n")

import scipy
import scipy.spatial

z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(z,z)
print(D)

[[0.         0.41907396 0.21497954 0.35233071 0.40407579 0.14474643
  0.42027161 0.6915105  0.79248557 0.57918977]
 [0.41907396 0.         0.62330547 0.72738748 0.39637215 0.45641098
  0.65565563 0.41325156 0.44188631 0.39347911]
 [0.21497954 0.62330547 0.         0.15896094 0.59283501 0.19509495
  0.3450134  0.90335144 1.00741975 0.69745948]
 [0.35233071 0.72738748 0.15896094 0.         0.74663144 0.27105116
  0.26094296 1.04276591 1.13603552 0.7194047 ]
 [0.40407579 0.39637215 0.59283501 0.74663144 0.         0.53715669
  0.81216141 0.3617738  0.50949908 0.76329709]
 [0.14474643 0.45641098 0.19509495 0.27105116 0.53715669 0.
  0.27725138 0.79081905 0.87232193 0.50492993]
 [0.42027161 0.65565563 0.3450134  0.26094296 0.81216141 0.27725138
  0.         1.03677746 1.09538321 0.51794139]
 [0.6915105  0.41325156 0.90335144 1.04276591 0.3617738  0.79081905
  1.03677746 0.         0.16274542 0.79021458]
 [0.79248557 0.44188631 1.00741975 1.13603552 0.50949908 0.87232193
  1.09538321 0.16274

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [130]:
x = np.arange(10,dtype=np.float32)
print(x)
x = x.astype(np.int32,copy=False)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [132]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11""")
x = np.genfromtxt(s, delimiter=",", dtype=np.int) #np.genfromtxt: 텍스트 파일을 numpy.array 형태로 변경
print(x)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


<ipython-input-132-18ada4666514>:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.genfromtxt(s, delimiter=",", dtype=np.int) #np.genfromtxt: 텍스트 파일을 numpy.array 형태로 변경


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [136]:
x = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(x): #np.ndenumerate(): 다차원 index 반환
    print(index,value)
    
print("\n")

for index in np.ndindex(x.shape):
    print(index,x[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [140]:
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(x*x + y*y)
sigma, mu = 1.0, 0.0
G = np.exp( -( (D-mu)**2 / (2.0*sigma**2) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [145]:
n = 10
p = 3
x = np.zeros((n,n))
np.put(x, np.random.choice(range(n*n), p, replace=False),1) #p: 각 데이터가 선택될 확률, replace=False: 비복원 추출
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [147]:
x = np.random.rand(5,10)
y = x - x.mean(axis=1, keepdims=True) #keepdims=True: 차원 유지
print(y)

[[ 0.38587164  0.46939069 -0.31884987  0.12399589 -0.26448007  0.47495623
   0.05951651 -0.21604299 -0.42525503 -0.28910298]
 [ 0.2940694   0.14293166  0.2961957   0.37683732 -0.16568517 -0.13226894
  -0.22773776 -0.32223142  0.06649732 -0.32860811]
 [-0.31886646  0.58569669 -0.30966227 -0.17962927 -0.12246417 -0.01216239
   0.06260917 -0.3056804   0.43353069  0.16662841]
 [ 0.012001   -0.35865201  0.4965279   0.27535267 -0.11086567  0.4759034
  -0.46023282  0.33238842 -0.23855935 -0.42386352]
 [-0.29445593 -0.32765123  0.28513118  0.45894796  0.43593216 -0.03090377
   0.42373035 -0.40975662 -0.36080736 -0.18016675]]


#### 59. How to sort an array by the nth column? (★★☆)

In [154]:
x = np.random.randint(0,10,(3,3))
print(x,"\n")
print(np.sort(x,axis=0)) #x[x[:,1].argsort()]

[[6 7 3]
 [8 1 2]
 [1 0 5]] 

[[1 0 2]
 [6 1 3]
 [8 7 5]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [164]:
x = np.random.randint(0,3,(3,10))
print(x,"\n")
print((~x.any(axis=0)).any()) #전부 0(null)인 column이 있는지

[[0 0 0 0 2 1 0 1 0 0]
 [1 2 0 0 0 1 0 2 0 0]
 [1 0 2 0 2 1 1 1 2 0]] 

True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [172]:
x = np.random.uniform(0,1,10)
y = 0.5
print("x:\n",x)
print("\ny:",y)
print("\nnearest value:",x[np.abs(x-y).argmin()])

x:
 [0.2478793  0.08250395 0.8089658  0.92486367 0.60553435 0.20667732
 0.91867235 0.53242826 0.79271197 0.16909673]

y: 0.5

nearest value: 0.5324282630547796


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [185]:
A = np.arange(3).reshape(1,3)
B = np.arange(3).reshape(3,1)
print("A:\n",A)
print("B:\n",B,"\n")

it = np.nditer([A,B,None]) #np.nditer(): 어디까지 반복해야하는지 return
for x,y,z in it: 
    z[...] = x + y #...: ':'와 같은 역할
print(it.operands[2])

A:
 [[0 1 2]]
B:
 [[0]
 [1]
 [2]] 

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [188]:
class nameArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', 'no name')

x = nameArray(np.arange(10),"new name")
print(x.name)

new name


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [192]:
x = np.ones(10)
y = np.random.randint(0,len(x),20)
print("x:",x)
print("y:",y)
print()
np.add.at(x,y,1) #x 배열의 y위치에 1씩 더하기
print("x:",x)
print("y:",y)

x: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
y: [0 2 4 2 6 4 6 8 3 2 1 2 3 4 8 5 5 7 7 9]

x: [2. 2. 5. 3. 4. 3. 3. 3. 3. 2.]
y: [0 2 4 2 6 4 6 8 3 2 1 2 3 4 8 5 5 7 7 9]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [206]:
X = [1,2,3,4,5,6]
I = [3,4,5,6,7,8]
F = np.bincount(I,X) #I 자리에 X 삽입 (index가 겹치면 더해줌)
print("X:",X)
print("I:",I)
print("F:",F)

X: [1, 2, 3, 4, 5, 6]
I: [3, 4, 5, 6, 7, 8]
F: [0. 0. 0. 1. 2. 3. 4. 5. 6.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [207]:
img = np.random.randint(0,2,(16,16,3)).astype(np.ubyte)
F = img[:,0]*(256*256) + img[:,1]*256 + img[:,2]
print(len(np.unique(F)))

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)