# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__) #numpy 버전 확인
np.show_config()

1.22.3
openblas64__info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SU

#### 3. Create a null vector of size 10 (★☆☆)

In [48]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [35]:
x = np.array([100,20,34])
  
print("Size of the array: ", x.size)
  
print("Memory size of one array element in bytes: ", x.itemsize)
  
# memory size of numpy array in bytes
print("Memory size of numpy array in bytes:", x.size * x.itemsize)

Size of the array:  3
Memory size of one array element in bytes:  4
Memory size of numpy array in bytes: 12


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [36]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [49]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [50]:
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [51]:
x = np.array([4,24,2,6,53,13])

print(x[::-1])
print(np.flip(x))

[13 53  6  2 24  4]
[13 53  6  2 24  4]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [53]:
x = np.arange(0,9)
x = x.reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [56]:
x = np.array([1,2,0,0,4,0])
for i in range(len(x)):
    if x[i] != 0:
        print(i)
        
print(np.where(x != 0))
print(np.nonzero(x))

0
1
4
(array([0, 1, 4], dtype=int64),)
(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [57]:
x = np.eye(3,3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [60]:
x = np.random.random([3,3,3])
print(x)

print("\n")

y = np.random.randint(27, size=(3,3,3))
print(y)

[[[0.94662197 0.97786784 0.28630518]
  [0.45100529 0.76428167 0.97041551]
  [0.08993333 0.47186816 0.66638136]]

 [[0.98669282 0.20472619 0.58080612]
  [0.60683866 0.84179036 0.8975152 ]
  [0.83783521 0.79502286 0.79771912]]

 [[0.31884396 0.45646864 0.3685764 ]
  [0.3561038  0.4646008  0.40736881]
  [0.43417455 0.58501488 0.21263581]]]


[[[15 24 14]
  [ 7  2  5]
  [ 8 15 15]]

 [[19 25 21]
  [11  9 26]
  [ 0  7  5]]

 [[22 16 14]
  [20 11 14]
  [ 3 20 24]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [61]:
x = np.random.random([10,10])
print("array:", x)
print("\n")
print("최소값:", np.min(x)) #x.min
print("최대값:", np.max(x)) #x.max

array: [[0.15250254 0.32803227 0.55203165 0.98206562 0.39584576 0.27646566
  0.86303708 0.8686586  0.36631571 0.35690862]
 [0.32779387 0.94045617 0.79364084 0.97880195 0.83867724 0.3164721
  0.58665779 0.7517017  0.4384464  0.71880395]
 [0.88514076 0.8652135  0.85559814 0.34247681 0.82954789 0.81638593
  0.52840133 0.51547782 0.56786423 0.38684491]
 [0.65441415 0.51515142 0.29897303 0.11979284 0.51503604 0.42991052
  0.70540125 0.3631962  0.37574112 0.61690631]
 [0.61078753 0.27733429 0.63385141 0.75513326 0.42053983 0.35553352
  0.71808947 0.04196451 0.0469651  0.35758764]
 [0.97631338 0.27417787 0.8640416  0.22034256 0.7223597  0.76524155
  0.52053282 0.69827936 0.206971   0.60803217]
 [0.65772559 0.55694676 0.07240525 0.29828289 0.67826528 0.99014616
  0.31333398 0.20042451 0.3764155  0.02504638]
 [0.45795969 0.7630016  0.31664127 0.66078811 0.79012653 0.13843316
  0.73676503 0.09407515 0.21345487 0.86785595]
 [0.15035533 0.37546743 0.98874572 0.99828655 0.96667937 0.24696312
  0.83

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [62]:
x = np.random.random(30)
print(x)
print("평균:",np.mean(x)) #x.mean

[0.59101568 0.84912965 0.65621789 0.0602328  0.07110058 0.53370394
 0.7472945  0.30417914 0.44191455 0.11222854 0.19151765 0.23620133
 0.59032453 0.71619254 0.76384941 0.3533908  0.59178301 0.22068257
 0.22640909 0.47565739 0.79691381 0.63852416 0.32533308 0.49613109
 0.19529569 0.29165299 0.72276359 0.61478036 0.85505104 0.80796797]
평균: 0.4825813121513779


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [65]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [68]:
x = np.ones((5,5))
y = np.pad(array=x, pad_width=1, mode='constant')
print(x)
print("\n")
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [71]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [72]:
x = np.array([1, 2, 3, 4])
np.diag(x)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [78]:
#x[a:b:c] -> index a부터 b-1까지 c칸 간격으로 추출
x = np.zeros((8,8))
x[1::2,::2] = 1 #row: 1부터 끝까지 2칸 간격으로, col: 처음부터 끝까지 2칸 간격으로
x[::2,1::2] = 1 #row: 처음부터 끝까지 2칸 간격으로, col: 1부터 끝까지 2칸 간격으로
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [81]:
x = np.unravel_index(99, (6,7,8)) #(6,7,8) shape array에서 100번째 element의 위치
print(x)

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
x = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(x)

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [85]:
x = np.random.random((5,5))
normal_x = (x - np.mean(x)) / np.std(x)
print("random matirx:\n", x)
print("\n")
print("normalized matrix:\n", normal_x)

random matirx:
 [[0.56584248 0.22300817 0.98265691 0.29851752 0.01635447]
 [0.57839633 0.72071472 0.82859114 0.26598339 0.6283073 ]
 [0.30170327 0.42662545 0.59486781 0.62322202 0.94310859]
 [0.08764997 0.10613468 0.68329499 0.55579322 0.66074683]
 [0.65687178 0.94935866 0.74288403 0.20021784 0.44958105]]


normalized matrix:
 [[ 0.15566423 -1.10820362  1.69226183 -0.82983639 -1.87003804]
 [ 0.20194434  0.72660491  1.12429421 -0.94977434  0.38594248]
 [-0.81809205 -0.35756306  0.26266691  0.36719545  1.54646587]
 [-1.60720527 -1.53906091  0.58865605  0.11861739  0.50553166]
 [ 0.49124619  1.56950693  0.80833267 -1.1922208  -0.27293664]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [86]:
col = np.dtype([('r', np.ubyte,1),
               ('g', np.ubyte,1),
               ('b', np.ubyte,1),
               ('a', np.ubyte,1)])
print(col)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


<ipython-input-86-6b7333104554>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  col = np.dtype([('r', np.ubyte,1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [87]:
A = np.random.random((5,3))
B = np.random.random((3,2))
print(A@B)
print("\n")
print(np.dot(A,B))

[[0.80440278 1.05427281]
 [0.80143242 1.06461897]
 [0.75037277 0.99990148]
 [0.80956596 1.04425262]
 [0.7048591  0.93172211]]


[[0.80440278 1.05427281]
 [0.80143242 1.06461897]
 [0.75037277 0.99990148]
 [0.80956596 1.04425262]
 [0.7048591  0.93172211]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [88]:
x = np.arange(11)
x[(x>3) & (x<8)] *= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [89]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [91]:
Z = np.array([1,2,3])
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z #오류 발생

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [92]:
np.array(0) / np.array(0) #nan
np.array(0) // np.array(0) #0
np.array([np.nan]).astype(int).astype(float)

<ipython-input-92-cd809174da5d>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
<ipython-input-92-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
x = np.random.uniform(-10,+10,10)
np.copysign(np.ceil(np.abs(Z)),Z)

#### 30. How to find common values between two arrays? (★☆☆)

In [43]:
array1 = np.array([0,10,20,40,60])
print("array1:", array1)
array2 = np.array([10,30,40])
print("array2:", array2)
print("Common values between two arrays:", np.intersect1d(array1, array2))

array1: [ 0 10 20 40 60]
array2: [10 30 40]
Common values between two arrays: [10 40]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
np.seterr(all="ignore") #오류 발생시 아무 행동도 취하지 않게 함

np.errstate(divide="ignore") #경고 표시 안함

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [44]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))
print(np.sqrt(-1) == np.emath.sqrt(-1))

nan
1j
False


<ipython-input-44-d41fcb2e2eaf>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))
<ipython-input-44-d41fcb2e2eaf>:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [45]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
next_year = np.datetime64('today', 'M') + np.timedelta64(1, 'M')

print(yesterday)
print(today)
print(tomorrow)
print(next_year)

2022-03-13
2022-03-14
2022-03-15
2022-04


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)