# 01 파이썬 기반의 머신러닝과 생태계 이해 <br>
## 03 넘파이  <br>
  
- **NumPy (Numerical Python, 넘파이)**:  <br>
    - 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
    - 루프를 사용하지 않고 대량 데이터의 배열 연산을 가능하게 하므로 빠른 배열 연산 속도를 보장함
    - C/C++과 같은 저수준 언어 기반의 호환 API를 제공하여 기존 C/C++ 기반의 타 프로그램과 데이터를 주고받거나 API를 호출해 쉽게 통합할 수 있는 기능 제공

### [넘파이 ndarray 개요] <br>
- numpy 모듈 임포트

In [1]:
import numpy as np

- `np.array()`: 파이썬의 리스트와 같은 다양한 인자를 입력 받아서 ndarray로 변환하는 기능 수행
- 생성된 ndarray 배열의 shape 변수는 ndarray의 크기, 즉 행과 열의 수를 튜플 형태로 가지고 있으며 이를 통해 ndarray 배열의 차원까지 알 수 있음

In [5]:
#ndarray.shape: ndarray의 차원과 크기를 튜플 형태로 변환

array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape) #1차원 array로 3개의 데이터를 가지고 있음

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape) #2차원 array로, 2*3으로 구성되어 있음 (총 6개의 데이터)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape) #2차원 array로, 1*3으로 구성되어 있음 (총 3개의 데이터)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [12]:
#ndarray.ndim: ndarray의 차원 반환

print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 1차원, array3:  1차원


### [ndarray의 데이터 타입] <br>
- ndarray 내의 데이터값은 숫자 값, 문자열 값, 불 값이 모두 가능함
- 숫자형의 경우 int형 (8bit, 16bit, 32bit), unsigned int형 (8bit, 16bit, 32bit), float형 (16bit, 32bit, 64bit, 128bit), 그리고 이보다 더 큰 숫자 값이나 정밀도를 위해 complex 타입도 제공
- ndarray 내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능 -> 한 개의 ndarray 객체에 int와 float 같이 있을 수 없음
- dtpye 속성을 사용하여 ndarray 내의 데이터 타입 확인 가능

In [13]:
#ndarray.dtype: ndarray 내의 데이터 타입 반환

list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype) #array1 내의 데이터 타입: int 32bit형

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [14]:
#서로 다른 데이터 타입이 섞여 있을 경우, 데이터 타입이 더 큰 데이터 타입으로 변환됨

list2 = [1,2,'test'] #int형과 string형이 섞여 있는 리스트
array2 = np.array(list2)
print(array2, array2.dtype) #숫자형 데이터 1,2가 모두 문자열 값 '1','2'로 변환

list3 = [1,2,3.0] #int형과 float형이 섞여 있는 리스트
array3 = np.array(list3)
print(array3, array3.dtype) #int형 데이터 1,2가 모두 float형 값 1.0,2.0으로 변환

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [18]:
#ndarray.astype(): ndarray 내 데이터값의 타입 변경

array_int = np.array([1,2,3])
array_float = array_int.astype('float64') #int32형을 float64형으로 변경
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32') #float64형을 int32형으로 변경
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float1.astype('int32') #float형을 int형으로 변경 -> 소수점 이하 없어짐
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### [ndarray를 편리하게 생성하기 - arange, zeros, ones] <br>
- `np.arange(n)`: 0부터 n-1까지의 값을 순차적으로 ndarray의 데이터값으로 변환
- default 함수 인자는 stop값이며, range와 유사하게 start 값도 부여해 0이 아닌 다른 값부터 시작 가능
```python
print(np.arange(1,10)) #start값, stop값 부여
#output: [1 2 3 4 5 6 7 8 9]
```

In [21]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


- `np.zeros((a,b), dtype='')`: 모든 값을 0으로 채운 (a,b) shape의 ndarray 반환
- `np.ones((a,b))`: 모든 값을 1로 채운 (a,b) shape의 ndarray 반환, dtype의 default: float64

In [23]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### [ndarray의 차원과 크기를 변경하는 reshape()] <br>
- `ndarray.reshape(a,b)`: ndarray를 특정 차원 및 크기 (a,b)로 변환
- 변환을 원하는 크기를 함수 인자로 부여하면 됨

In [25]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [26]:
array1.reshape(4,3) #지정된 사이즈로 변경이 불가능하면 오류 발생

ValueError: cannot reshape array of size 10 into shape (4,3)

In [28]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5) #column 개수가 5개가 되도록 row를 자유롭게 생성해 변환
print('array2 shape:', array2.shape)
array3 = array1.reshape(5,-1) #row 개수가 5개가 되도록 row를 자유롭게 생성해 변환
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [31]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4) #4개의 column을 가지게 변경이 불가능하므로 오류 발생

ValueError: cannot reshape array of size 10 into shape (4)

In [33]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array shape:', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### [넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)] <br>
- `ndarray[i]`: index가 i인 데이터 반환
- `ndarray[a:b]` **슬라이싱 (Slicing)** : index가 a부터 b-1인 데이터 반환
- `ndarray[[a,b],c:d]` **팬시 인덱싱 (Fancy Indexing)** : row index가 a,b이고 column index가 c:d인 데이터 반환
- `ndarray[ndarray > a]` **불린 인덱싱 (Boolean Indexing)** : ndarray에서 값이 a보다 큰 데이터만 추출

#### 단일 값 추출

In [34]:
#1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [37]:
#ndarray[-i]: 맨 뒤에서 i번째 값 추출
print('맨 뒤의 값:', array1[-1], ', 맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 , 맨 뒤에서 두 번째 값: 8


In [39]:
#ndarray 내의 데이터값 수정
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [42]:
#axis 0: row 방향 축, axis 1: column 방향 축

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


#### 슬라이싱
- ':' 기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주
- ':' 기호 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주
- ':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주

In [44]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [45]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [46]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2,0:2] \n', array2d[0:2,0:2])
print('array2d[1:3,0:3] \n', array2d[1:3,0:3])
print('array2d[1:3,:] \n', array2d[1:3,:])
print('array2d[:,:] \n', array2d[:,:])
print('array2d[:2,1:] \n', array2d[:2,1:])
print('array2d[:2,0] \n', array2d[:2,0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2] 
 [[1 2]
 [4 5]]
array2d[1:3,0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:] 
 [[4 5 6]
 [7 8 9]]
array2d[:,:] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:] 
 [[2 3]
 [5 6]]
array2d[:2,0] 
 [1 4]


In [48]:
#2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray 반환
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape,', array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) , array2d[1] shape: (3,)


#### 팬시 인덱싱

In [49]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2] =>', array3.tolist())

array4 = array2d[[0,1],0:2]
print('array2d[[0,1],0:2] =>', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] =>', array5.tolist())

array2d[[0,1],2] => [3, 6]
array2d[[0,1],0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


#### 불린 인덱싱
- Step 1: array1d > 5와 같이 ndarray의 필터링 조건을 [] 안에 기재
- Step 2: False 값은 무시하고 True 값에 해당하는 index 값만 저장
- Step 3: 저장된 index 데이터 세트로 ndarray 조회

In [53]:
array1d = np.arange(start=1, stop=10)
#[ ] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [52]:
array1d > 5 #Boolean 값 반환

array([False, False, False, False, False,  True,  True,  True,  True])

In [54]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [55]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 : ', array4)

일반 인덱스로 필터링 결과 :  [6 7 8 9]


### [행렬의 정렬 - sort()와 argsort()] <br>
#### 행렬 정렬
- `np.sort(ndarray)`: 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬 반환
- `ndarray.sort()`: 원 행렬 자체를 정렬한 형태로 변환하여 반환 값은 None

In [59]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

#np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array) #원본 행렬 그대로 유지

#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2) #반환 값은 None
print('org_array.sort() 호출 후 원본 행렬:', org_array) #원본 행렬 자체를 정렬

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [60]:
sort_array1_desc = np.sort(org_array)[::-1] #내림차순으로 정렬
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [62]:
array2d = np.array([[8,12],
                   [7,1]])

sort_array2d_axis0 = np.sort(array2d, axis=0) #row끼리 정렬
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1) #column끼리 정렬
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


#### 정렬된 행렬의 인덱스를 반환하기
- `np.argsort()`: 정렬 행렬의 원본 인덱스를 ndarray형으로 반환

In [66]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array) #데이터의 오름차순 인덱스 반환
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [65]:
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1] #데이터의 내림차순 인덱스 반환
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [68]:
import numpy as np

name_array = np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### [선형대수 연산 - 행렬 내적과 전치 행렬 구하기] <br>
#### 행렬 내적(행렬 곱)
- `np.dot(A,B)`: A 행렬과 B 행렬의 내적 결과 반환
- 행렬 내적 시에는 왼쪽 행렬의 열 개수와 오른쪽 행렬의 행 개수가 동일해야 연산이 가능함

In [69]:
A = np.array([[1,2,3],
             [4,5,6]])
B = np.array([[7,8],
             [9,10],
             [11,12]])

dot_product = np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


#### 전치 행렬
- `np.transpose(A)`: A 행렬의 전치 행렬 반환

In [70]:
A = np.array([[1,2],
             [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
